### ISSUE TITLE
[BUG] How to setup username/password when accessing Filezilla?

### ISSUE THREAD

**Issue by githupper** [linuxserver/docker-filezilla#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When accessing http://yourhost:3000, user is immediately shown with the Filezilla interface. How to set it such that any access to http://yourhost:3000/ is mandatory with a login prompt (and also how to change the username and password from abc/abc).

There is no option to change the username or password at http://yourhost:3000/?login=true either.

Thanks

### Steps To Reproduce

Access http://yourhost:3000

### Environment

```markdown
- OS: Fedora
- How docker service was installed: Docker
---
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  filezilla:
    image: lscr.io/linuxserver/filezilla:latest
    container_name: filezilla
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/githupper/Docker/Filezilla/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped
```

### Container logs

```bash
nil
```

**Comment by AggelosM** [comment]
Any update on this? I'm having the same issue. I don't want anyone accessing my network to be able to just delete all my downloaded files.

**Comment by thelamer** [comment]
The new image has the ability to pass in basic auth credentials please review the new readme.
