### ISSUE TITLE
Request for CJK support

### ISSUE THREAD

**Issue by githupper** [linuxserver/docker-filezilla#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

To request for CJK unicode support

### Expected Behavior

Languages other than alphabets to be displayed

### Steps To Reproduce

NIL

### Environment

```markdown
- OS: Fedora
- How docker service was installed: Docker Compose
```

### CPU architecture

x86-64

### Docker creation

```bash
NIL
```

### Container logs

```bash
NIL
```

**Comment by thelamer** [comment]
CJK can be installed with `sudo apk add font-noto-cjk` from the terminal. 

To achieve this unmaximize the filezilla window > right click on the desktop > select xterm, run the command above. 

CJK and other language compatibility fonts are massive and will not be making it into the stock images, but you might want to make a mod or ask the maintainer of this mod to make one that also includes CJK: 

https://github.com/linuxserver/docker-mods/tree/firefox-fonts

**Comment by githupper** [comment]
@thelamer Thank you for your generosity in rendering assistance.

I have tested it working now.

Will proceed to close this ticket.

Once again, really appreciate the assistance.

**Comment by thelamer** [comment]
@githupper FYI: 
https://github.com/linuxserver/docker-mods/tree/universal-internationalization

So for Chinese pass: 
```
-e LC_ALL=zh_CN.UTF-8
-e DOCKER_MODS=linuxserver/mods:universal-internationalization
```

This will completely localize the application on top of installing fonts: 

![chinese](https://user-images.githubusercontent.com/1852688/232561813-56b603d2-0106-4584-b7ba-e655d9350757.png)

Many other languages are supported: 

https://github.com/linuxserver/docker-mods/tree/universal-internationalization#other-languages
