### ISSUE TITLE
Save Password option gone

### ISSUE THREAD

**Issue by xLogiiCx** [linuxserver/docker-filezilla#3]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The WebUI Site Manager does not let me save Passwords, only usernames. 
This happened after the last Update.

------------------------------

## Expected Behavior
Opening the Site Manger ->
Creating new Site ->
Adding Username -> 
Adding Password ->
(Maybe) Protect it by master Password ->
Connect to Site -> Password should be automatically used. 
Also when trying to connect to a Server with only the username set it will try to auth with that username but an empty password.

## Current Behavior
Site Manager Password Option gone. 

## Steps to Reproduce

1. Open WebUI
2. Open SiteManager
3. Search for the Field to put a Password in. 
4.

## Environment
**OS:** Unraid
**CPU architecture:** x86_64

## Command used to create docker container (run/create/compose/screenshot)

```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='filezilla' --net='br0' --ip='192.168.179.60' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -e 'TCP_PORT_3000'='3000' -v '/mnt/user/appdata/filezilla':'/config':'rw' -v '/mnt/user/Media/Download':'/Media':'rw' 'linuxserver/filezilla'
```

cc1d0a8add11ca108c958781753814b403984cfb4734fae5e607679b3fa0bff9

**Comment by wsxws** [comment]
i got the same error.
workaround: type new servers into quick-connect and save that connection to servermanager after connection.

**Comment by thelamer** [comment]
I honestly have no idea what either of you are talking about, what is a site manager and how does this apply to this application?

**Comment by thelamer** [comment]
Ahh in filezilla, ok I'm dumb I thought you were talking about an external wrapper or reverse proxy or someting. This image simply pulls the latest version from alpine's repos, I don't have any plans to pin the version to something older than latest.
