### ISSUE TITLE
No change of language possible

### ISSUE THREAD

**Issue by wsxws** [linuxserver/docker-filezilla#4]
no other language than english available
folder 'locales' is missing

## Expected Behavior
settings - lamguage - different languages to choose

## Current Behavior
settings - language - no other language than english

## Environment
**OS:**
unraid
**CPU architecture:**
x86_64

**Comment by wsxws** [comment]
workaround (example for german language file):
find yourself a german filezilla.mo (download from the web, grab a portable version an cope it off App/filezilla/locales or on linux systems look at the following destination-path
copy that file on your docker (using filezilla ie ;))
open docker-shell and copy the german filezilla.mo to /usr/share/locale/de/LC_MESSAGES/
restart filezilla-docker
in settings change language to german
restart filezilla-docker
done ;)

**Comment by thelamer** [comment]
languages have been added in the latest version
