### ISSUE TITLE
Max Download per File ist only 10mib/s

### ISSUE THREAD

**Issue by LIONNNNNN** [linuxserver/docker-filezilla#6]
## Expected Behavior
Filezilla only downloads with 10MiB/s

## Current Behavior
Filezilla only downloads with 10MiB/s

## Steps to Reproduce

1. Launch Docker Container with Filezilla
2. Check if the Speed Limit ist enabled
3. Download an file
4. See the max of 10 MiB/s

## Environment
**OS: TrueNas Scale**
**CPU architecture: x86** 
**Internal-Network: 10GBit**
**External-Network: 1GBit**
**How docker service was installed: From the TrueCharts App Store**

**Comment by drizuid** [comment]
can you replicate the issue using docker compose or docker run on a standard debian based machine? We do not make anything for the truecharts app store and have no knowledge of what issues truenas scale could be presenting or what issues the template author may have caused..
